services:
  allhands22:
    image: ${TESTING_IMAGE}

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./healthcheck:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: "5s"
    sut:
      image: ${TESTING_IMAGE}
      depends_on:
        allhands22:
          condition: service_started
        postgres:
          condition: service_healthy
      command: curl --fail http://allhands22:80 || exit 1
