---
name: Basic Docker Build

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}  # will not push it until merged
          tags: valantis/allhands22:latest,valantis/allhands22:01
        